import { test, expect } from "@playwright/test";
import {fixture} from "../tests/fixture.mjs";
test("slide navigation stays quiet and does not shift the desk", async ({browser}) => {
 const {studio,address}=await fixture();
 const context=await browser.newContext();
 try {
   const desk=await context.newPage();
   for (const width of [1600, 390]) {
     await desk.setViewportSize({width,height:1050});
     await desk.goto(address.deskUrl);
     await desk.locator("#present-mode").click();
     const cue=desk.locator("#previous-beat");
     await expect(cue).toBeVisible();
     const before=await cue.evaluate(el=>el.getBoundingClientRect().top+window.scrollY);
     await cue.click();
     await expect(desk.locator("#notice")).toBeHidden();
     const after=await cue.evaluate(el=>el.getBoundingClientRect().top+window.scrollY);
     expect(after).toBe(before);
     await expect(desk.locator("#notice")).toHaveCSS("position","fixed");
   }
   const stage=await context.newPage();await stage.goto(address.stageUrl);
   const previous=await stage.locator("h1").textContent();
   await expect(desk.locator("#audience-slide")).toHaveCount(0);
   await expect(stage.locator("h1")).toHaveText(previous);
   await desk.locator("#next-beat").click();
   await expect(stage.locator("h1")).toHaveText("When you use the web today, what feels unnecessarily difficult?");
   await expect(stage.locator("body")).toContainText("Take at least two minutes to discuss with a neighbour.");
   await desk.locator("#previous-beat").click();
   await expect(stage.locator("h1")).toHaveText("Web development: past, present, and possible futures");
 } finally {await context.close();await new Promise(resolve=>studio.server.close(resolve));}
});
test("private selection, deliberate projection, graphic rendering and approval handoff", async ({browser}) => {
 const {studio,address,bridge}=await fixture({rehearsals:{create:async()=>"/test/rehearsal-001"}});
 const context=await browser.newContext({viewport:{width:1600,height:1050}});
 try {
   const desk=await context.newPage(), stage=await context.newPage();
   const errors=[]; desk.on("pageerror",e=>errors.push(e.message));stage.on("pageerror",e=>errors.push(e.message));
   await desk.goto(address.deskUrl);await stage.goto(address.stageUrl);
   await desk.locator("#prepare-mode").click();
   await expect(desk.locator("#preview h1")).toHaveText("Who is the interface for?");
   await expect(stage.locator("h1")).toHaveText("Who is the interface for?");
   await desk.locator("#connections summary").click();
   await expect(desk.locator("#notes-signal")).toContainText("Obsidian");
   await expect(desk.locator("#codex-signal")).toContainText("disconnected");
   await desk.getByRole("button",{name:"Connect Obsidian",exact:true}).click();
   await desk.locator("#connections summary").click();
   await desk.getByRole("button",{name:"Example",exact:true}).click();
   await expect(desk.locator("#note-content")).toContainText("A capability that survives.");
   await desk.getByRole("button",{name:"Use section in draft"}).click();
   await expect(desk.locator("#preview")).toContainText("A capability that survives.");
   await expect(stage.locator("h1")).toHaveText("Who is the interface for?");
   await desk.locator("#publish").click();await expect(stage.locator("h1")).toHaveText("Progressive enhancement");
   await desk.locator("#sections").selectOption({label:"Visual"});
   await expect(desk.locator("#note-content svg")).toHaveCount(1);
   await desk.locator("#use-section").click();await desk.locator("#publish").click();
   await expect(stage.locator("svg")).toHaveCount(1);
   await desk.locator("#mode").selectOption("diagram");await desk.locator("#diagram").selectOption("enhancement");
   await desk.locator("#body").fill("");await desk.locator("#publish").click();
   await expect(stage.locator(".layer")).toHaveCount(3);
   await desk.locator("#connections summary").click();await desk.locator("#connect-codex").click();
   await expect(desk.locator("#codex-signal")).toHaveText("Codex · ready");
   await desk.keyboard.press("Escape");
   await expect(desk.locator("#connect-codex")).not.toBeVisible();
   await desk.locator("#brief").fill("PRIVATE implementation brief.");
   await desk.locator("#send").click();
   await expect(desk.locator("#requests")).toContainText("private-test-command");
   await expect(stage.locator("body")).not.toContainText("PRIVATE implementation");
   await expect(stage.locator("body")).not.toContainText("private-test-command");
   await desk.getByRole("button",{name:"Approve once",exact:true}).click();
   await expect(desk.locator("#messages")).toContainText("Fixture implementation complete.");
   await desk.locator("#brief").fill("A different, unsent prompt.");
   await desk.locator("#show-brief").click();
   await expect(stage.locator(".brief-copy")).toHaveText("A different, unsent prompt.");
   await desk.locator("#show-sent-brief").click();
   await expect(stage.locator(".brief-copy")).toHaveText("PRIVATE implementation brief.");
   await expect(desk.locator("#brief")).toHaveValue("A different, unsent prompt.");
   await desk.locator("#back-material").click();
   await expect(stage.locator(".layer")).toHaveCount(3);
   await desk.locator("#blank").click();await expect(stage.locator("body")).toHaveClass(/blank/);
   await expect(stage.locator("#stage-content")).toHaveCSS("visibility","hidden");
   await desk.locator("#blank").click();await expect(stage.locator("body")).not.toHaveClass(/blank/);
   await expect(stage.locator("#stage-content")).toHaveCSS("visibility","visible");
   expect(await stage.locator("h1").evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThan(70);
   await desk.screenshot({path:"test-results/desk.png",fullPage:true});
   await desk.locator("#present-mode").click();
   await expect(desk.locator("#current-stage-panel")).toBeVisible();
   await expect(desk.locator("#preview")).toBeHidden();
   await expect(desk.locator("#current-stage .layer")).toHaveCount(3);
   await expect(desk.locator("#use-question")).toHaveCount(0);
   await expect(desk.locator(".live-overview #blank")).toBeVisible();
   await expect(desk.locator("#publish")).toHaveCount(1);
   await expect(desk.locator(".plot")).toBeHidden();
   await expect(desk.locator("#search")).toBeHidden();
   await expect(desk.locator("#brief")).toBeVisible();
   let published = await stage.locator("h1").textContent();
   await desk.locator("#next-beat").click();
   await expect(desk.locator("#live-next")).toContainText("unnecessarily difficult");
   published = "When you use the web today, what feels unnecessarily difficult?";
   await expect(desk.locator("#preview")).toContainText("unnecessarily difficult");
   await expect(stage.locator("h1")).toHaveText(published);
   await desk.locator("#find-material").click();
   await expect(desk.locator("#current-stage-panel")).toBeHidden();
   await expect(desk.locator("#preview")).toBeVisible();
   await expect(desk.locator(".material-column #publish")).toBeVisible();
   await expect(desk.locator("#search")).toBeVisible();
   await desk.keyboard.press("Escape");
   await expect(desk.locator("#next-beat")).toBeVisible();
   await expect(desk.locator("#search")).toBeHidden();
   let previewLoads = 0;
   await context.route("http://localhost:8799/**", route => { previewLoads++; return route.fulfill({contentType:"text/html",body:"<h1>Live fixture app</h1>"}); });
   bridge.state.messages = [{id:"preview",text:"Preview: http://localhost:8799/rooms/demo"}];
   await expect(desk.locator("#preview-shortcuts")).toBeVisible();
   expect(previewLoads).toBe(0);
   await expect(stage.locator("iframe")).toHaveCount(0);
   await desk.locator("#show-preview").click();
   await expect(stage.frameLocator("iframe").locator("h1")).toHaveText("Live fixture app");
   await expect(desk.locator("#current-stage")).toContainText("Live app is on the projected stage.");
   await expect(desk.locator("#current-stage iframe")).toHaveCount(0);
   await expect(desk.locator("#preview")).toContainText("unnecessarily difficult");
   await expect(desk.locator("#open-preview")).toHaveAttribute("rel","noopener noreferrer");
   await desk.locator("#back-material").click();
   await expect(stage.locator("h1")).toHaveText(published);
   await expect(stage.locator("iframe")).toHaveCount(0);
   await desk.screenshot({path:"test-results/present.png",fullPage:true});
   await stage.screenshot({path:"test-results/stage.png",fullPage:true});
   await expect(desk.locator("#new-rehearsal")).toBeHidden();
   await desk.locator("#prepare-mode").click();
   desk.once("dialog",dialog=>dialog.dismiss());
   await desk.locator("#reset-lecture").click();
   await expect(desk.locator("#live-next")).toContainText("unnecessarily difficult");
   desk.once("dialog",dialog=>dialog.accept());
   await desk.locator("#reset-lecture").click();
   await expect(stage.locator("h1")).toHaveText("Who is the interface for?");
   await expect(desk.locator("#preview-shortcuts")).toBeHidden();
   desk.once("dialog",dialog=>dialog.accept());
   await desk.locator("#new-rehearsal").click();
   await expect(desk.locator("#rehearsal-status")).toHaveText("Fresh rehearsal ready.");
   await expect(desk.locator("#workspace")).toHaveText("/test/rehearsal-001");
   expect(errors).toEqual([]);
 } finally {await context.close();await new Promise(resolve=>studio.server.close(resolve));}
});
