import { test, expect } from "@playwright/test";
import {fixture} from "../tests/fixture.mjs";
test("private selection, deliberate projection, graphic rendering and approval handoff", async ({browser}) => {
 const {studio,address,bridge}=await fixture();
 const context=await browser.newContext({viewport:{width:1600,height:1050}});
 try {
   const desk=await context.newPage(), stage=await context.newPage();
   const errors=[]; desk.on("pageerror",e=>errors.push(e.message));stage.on("pageerror",e=>errors.push(e.message));
   await desk.goto(address.deskUrl);await stage.goto(address.stageUrl);
   await desk.locator("#prepare-mode").click();
   await expect(desk.locator("#preview h1")).toHaveText("Who is the interface for?");
   await expect(stage.locator("h1")).toHaveText("Who is the interface for?");
   await desk.getByRole("button",{name:"Connect Obsidian",exact:true}).click();
   await desk.getByRole("button",{name:"Example",exact:true}).click();
   await expect(desk.locator("#note-content")).toContainText("A capability that survives.");
   await desk.getByRole("button",{name:"Use section in draft"}).click();
   await expect(desk.locator("#preview")).toContainText("A capability that survives.");
   await expect(stage.locator("h1")).toHaveText("Who is the interface for?");
   await desk.locator("#publish").click();await expect(stage.locator("h1")).toHaveText("Progressive enhancement");
   await desk.locator("#sections").selectOption({label:"Visual"});
   await expect(desk.locator("#note-content svg")).toHaveCount(1);
   await desk.locator("#use-section").click();await desk.locator("#publish").click();
   await expect(stage.locator("svg")).toHaveCount(1);
   await desk.locator("#mode").selectOption("diagram");await desk.locator("#diagram").selectOption("enhancement");
   await desk.locator("#body").fill("");await desk.locator("#publish").click();
   await expect(stage.locator(".layer")).toHaveCount(3);
   await desk.locator(".connection summary").click();await desk.locator("#connect-codex").click();
   await desk.locator("#brief").fill("PRIVATE implementation brief.");
   await desk.locator("#send").click();
   await expect(desk.locator("#requests")).toContainText("private-test-command");
   await expect(stage.locator("body")).not.toContainText("PRIVATE implementation");
   await expect(stage.locator("body")).not.toContainText("private-test-command");
   await desk.getByRole("button",{name:"Approve once",exact:true}).click();
   await expect(desk.locator("#messages")).toContainText("Fixture implementation complete.");
   await desk.locator("#blank").click();await expect(stage.locator("body")).toHaveClass(/blank/);
   await expect(stage.locator("#stage-content")).toHaveCSS("visibility","hidden");
   await desk.locator("#blank").click();await expect(stage.locator("body")).not.toHaveClass(/blank/);
   await expect(stage.locator("#stage-content")).toHaveCSS("visibility","visible");
   expect(await stage.locator("h1").evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThan(70);
   await desk.screenshot({path:"test-results/desk.png",fullPage:true});
   await desk.locator("#present-mode").click();
   await expect(desk.locator(".cue-stage-controls #publish")).toBeVisible();
   await expect(desk.locator(".cue-stage-controls #blank")).toBeVisible();
   await expect(desk.locator("#publish")).toHaveCount(1);
   await expect(desk.locator(".plot")).toBeHidden();
   await expect(desk.locator("#search")).toBeHidden();
   await expect(desk.locator("#brief")).toBeVisible();
   const published = await stage.locator("h1").textContent();
   await desk.locator("#next-beat").click();
   await expect(desk.locator("#live-next")).toContainText("address");
   await desk.locator("#use-question").click();
   await expect(desk.locator("#preview")).toContainText("address");
   await expect(stage.locator("h1")).toHaveText(published);
   await desk.locator("#find-material").click();
   await expect(desk.locator(".material-column #publish")).toBeVisible();
   await expect(desk.locator("#search")).toBeVisible();
   await desk.keyboard.press("Escape");
   await expect(desk.locator(".cue-stage-controls #publish")).toBeVisible();
   await expect(desk.locator("#search")).toBeHidden();
   let previewLoads = 0;
   await context.route("http://localhost:8799/**", route => { previewLoads++; return route.fulfill({contentType:"text/html",body:"<h1>Live fixture app</h1>"}); });
   bridge.state.messages = [{id:"preview",text:"Preview: http://localhost:8799/rooms/demo"}];
   await expect(desk.locator("#preview-shortcuts")).toBeVisible();
   expect(previewLoads).toBe(0);
   await expect(stage.locator("iframe")).toHaveCount(0);
   await desk.locator("#show-preview").click();
   await expect(stage.frameLocator("iframe").locator("h1")).toHaveText("Live fixture app");
   await expect(desk.locator("#preview")).toContainText("address");
   await expect(desk.locator("#open-preview")).toHaveAttribute("rel","noopener noreferrer");
   await desk.locator("#back-material").click();
   await expect(stage.locator("h1")).toHaveText(published);
   await expect(stage.locator("iframe")).toHaveCount(0);
   await desk.screenshot({path:"test-results/present.png",fullPage:true});
   await stage.screenshot({path:"test-results/stage.png",fullPage:true});
   expect(errors).toEqual([]);
 } finally {await context.close();await new Promise(resolve=>studio.server.close(resolve));}
});
